version: "3.8"
services:
  frontend:
    image: sandeep9298/speakez:1.04
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    image: sandeep9298/speakez-backend:1.01
    networks:
      - my-network

networks:
  my-network:
